(function(){'use strict';
var ENDPOINT='https://script.google.com/macros/s/AKfycbyHicngCVMmfbtBU1VuuL-Ma7-UckHde8SKVsIocotw_DMFi2eWJaM8SooKTp-mTrR1/exec';
var S={shape:'vessel',height:90,radius:38,belly:.08,rough:.45,seed:18273,wall:3,floor:5,eyes:false,mouth:false,ears:false,nose:false,eyeStyle:'round',mouthStyle:'normal',earStyle:'round',faceSize:8,faceHeight:.56,jomon:false,jomonStyle:'diagonal',jomonSpace:9,jomonSize:2.4,color:'#b56f45'};
var colors=[['#b56f45','赤土'],['#d59a68','黄土'],['#d8d0ba','白土'],['#6e7469','灰土'],['#446d62','深緑'],['#76536f','葡萄']];
var canvas=document.getElementById('view'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,1500),renderer=new THREE.WebGLRenderer({canvas:canvas,antialias:true,preserveDrawingBuffer:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputEncoding=THREE.sRGBEncoding;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
camera.up.set(0,0,1);camera.position.set(145,-190,115);var controls=new THREE.OrbitControls(camera,canvas);controls.enableDamping=true;controls.target.set(0,0,45);controls.minDistance=90;controls.maxDistance=460;
scene.add(new THREE.HemisphereLight(0xfff7e8,0x33443b,1.35));var key=new THREE.DirectionalLight(0xffffff,1.5);key.position.set(-100,-130,190);key.castShadow=true;scene.add(key);var fill=new THREE.DirectionalLight(0xd9c1ff,.45);fill.position.set(120,80,80);scene.add(fill);
var ground=new THREE.Mesh(new THREE.CylinderGeometry(82,86,4,64),new THREE.MeshStandardMaterial({color:0x777b6e,roughness:.92}));ground.rotation.x=Math.PI/2;ground.position.z=-3;ground.receiveShadow=true;scene.add(ground);
var model=new THREE.Group();scene.add(model);var rebuildTimer=0,roughCoeffs=[];
function rng(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;var t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function makeNoise(){var r=rng(S.seed);roughCoeffs=[];for(var m=2;m<=7;m++)roughCoeffs.push({m:m,a:.35+r()*.65,p:r()*Math.PI*2,mz:1+Math.floor(r()*3),pz:r()*Math.PI*2})}
function roughAt(a,t){if(S.shape!=='lump'||!S.rough)return 0;var n=0,w=0;roughCoeffs.forEach(function(c){n+=c.a*Math.sin(c.m*a+c.p)*Math.sin(c.mz*Math.PI*t+c.pz);w+=c.a});var fade=Math.pow(Math.max(0,Math.sin(Math.PI*t)),.38)*Math.min(1,t/.16);return S.radius*.22*S.rough*fade*n/Math.max(.001,w)}
function profile(t,a){if(S.shape==='vessel')return Math.max(8,S.radius*(1+S.belly*Math.sin(Math.PI*t)-.08*Math.cos(Math.PI*t)));var shoulder=Math.pow(Math.max(0,Math.sin(Math.PI*t)),.4),belly=Math.exp(-.5*Math.pow((t-.48)/.36,2));var r=S.radius*(.035+.25*Math.pow(1-t,2)+.78*shoulder+.14*belly*Math.pow(Math.max(.001,1-t),.32));return Math.max(1.2+(S.wall+4-1.2)*Math.pow(1-t,2),r+roughAt(a,t))}
function vtx(r,a,z){return new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),z)}
function clayGeometry(){var seg=72,lv=52,pos=[],outer=[];function tri(a,b,c){pos.push(a.x,a.y,a.z,b.x,b.y,b.z,c.x,c.y,c.z)}
 for(var i=0;i<lv;i++){var t=i/(lv-1),ring=[];for(var j=0;j<seg;j++){var a=j/seg*Math.PI*2;ring.push(vtx(profile(t,a),a,S.height*t))}outer.push(ring)}
 for(i=0;i<lv-1;i++)for(j=0;j<seg;j++){var n=(j+1)%seg;tri(outer[i][j],outer[i][n],outer[i+1][n]);tri(outer[i][j],outer[i+1][n],outer[i+1][j])}
 var c0=new THREE.Vector3(0,0,0);for(j=0;j<seg;j++)tri(c0,outer[0][(j+1)%seg],outer[0][j]);
 if(S.shape==='vessel'){var inner=[],start=Math.max(1,Math.round((S.floor/S.height)*(lv-1)));for(i=start;i<lv;i++){var tt=i/(lv-1),ir=[];var thick=S.wall*(1-.22*tt);for(j=0;j<seg;j++){var aa=j/seg*Math.PI*2;ir.push(vtx(Math.max(2,profile(tt,aa)-thick),aa,S.height*tt))}inner.push(ir)}for(i=0;i<inner.length-1;i++)for(j=0;j<seg;j++){n=(j+1)%seg;tri(inner[i][j],inner[i+1][n],inner[i][n]);tri(inner[i][j],inner[i+1][j],inner[i+1][n])}var last=inner.length-1;for(j=0;j<seg;j++){n=(j+1)%seg;tri(outer[lv-1][j],inner[last][n],outer[lv-1][n]);tri(outer[lv-1][j],inner[last][j],inner[last][n])}var cf=new THREE.Vector3(0,0,S.height*start/(lv-1));for(j=0;j<seg;j++)tri(cf,inner[0][j],inner[0][(j+1)%seg]);}
 else{var top=new THREE.Vector3(0,0,S.height);for(j=0;j<seg;j++)tri(top,outer[lv-1][j],outer[lv-1][(j+1)%seg]);}
 var g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();return g}
 function clayMat(){return new THREE.MeshStandardMaterial({color:S.color,roughness:.78,metalness:0,side:THREE.DoubleSide})}
 function addSphere(name,a,z,tan,vert,rad){var r=profile(Math.max(0,Math.min(1,z/S.height)),a),g=new THREE.SphereGeometry(1,22,14),m=new THREE.Mesh(g,clayMat());m.name=name;m.scale.set(rad,tan,vert);m.rotation.z=a;m.position.set((r+rad*.52)*Math.cos(a),(r+rad*.52)*Math.sin(a),z);m.castShadow=true;model.add(m)}
 function addFace(){var q=S.faceSize,z=S.height*S.faceHeight,r0=Math.max(10,profile(S.faceHeight,0)),sep=Math.min(.82,q/r0);if(S.eyes){var d=S.eyeStyle==='wide'?[q*.32,q*.78,q*.55]:S.eyeStyle==='narrow'?[q*.28,q*.72,q*.27]:[q*.34,q*.48,q*.6];addSphere('eyeL',-sep,z+q*.25,d[1],d[2],d[0]);addSphere('eyeR',sep,z+q*.25,d[1],d[2],d[0])}if(S.mouth){var md=S.mouthStyle==='wide'?[q*.3,q*1.75,q*.34]:S.mouthStyle==='small'?[q*.34,q*.48,q*.48]:[q*.3,q*1.15,q*.35];addSphere('mouth',0,z-q*.85,md[1],md[2],md[0])}if(S.nose)addSphere('nose',0,z-q*.15,q*.38,q*.48,q*.48);if(S.ears){var ed=S.earStyle==='rabbit'?[q*.42,q*.48,q*1.65]:S.earStyle==='wide'?[q*.45,q*.85,q*.72]:[q*.42,q*.42,q*.78],side=S.earStyle==='rabbit'?1.05:Math.PI/2,ez=S.earStyle==='rabbit'?Math.min(S.height-q*.2,z+q*1.15):z;addSphere('earL',-side,ez,ed[1],ed[2],ed[0]);addSphere('earR',side,ez,ed[1],ed[2],ed[0])}}
 function surfacePoint(a,z,offset){var t=Math.max(.015,Math.min(.985,z/S.height)),r=profile(t,a)+offset;return new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),z)}
 function tube(points,r){var curve=new THREE.CatmullRomCurve3(points,false,'centripetal'),g=new THREE.TubeGeometry(curve,Math.max(24,points.length*2),r,8,false),m=new THREE.Mesh(g,clayMat());m.name='jomon';m.castShadow=true;model.add(m)}
 function addJomon(){if(!S.jomon)return;var lo=S.height*.16,hi=S.height*.78,space=S.jomonSpace,rr=S.jomonSize*.5,off=-rr*.28;if(S.jomonStyle==='horizontal'){for(var z=lo;z<=hi;z+=space){var pts=[];for(var j=0;j<=72;j++)pts.push(surfacePoint(j/72*Math.PI*2,z,off));var c=new THREE.CatmullRomCurve3(pts,true,'centripetal'),g=new THREE.TubeGeometry(c,144,rr,8,true),m=new THREE.Mesh(g,clayMat());m.name='jomon';model.add(m)}}else{var turns=(hi-lo)/space,dirs=S.jomonStyle==='cross'?[1,-1]:[1];dirs.forEach(function(dir){for(var strand=0;strand<2;strand++){var pts=[];for(var k=0;k<=Math.ceil(turns*60);k++){var t=k/Math.ceil(turns*60),a=Math.PI*strand+dir*Math.PI*2*turns*t;pts.push(surfacePoint(a,lo+(hi-lo)*t,off))}tube(pts,rr)}})}}
 function dispose(){while(model.children.length){var o=model.children.pop();if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()}}
 function rebuild(){dispose();makeNoise();var body=new THREE.Mesh(clayGeometry(),clayMat());body.name='clay';body.castShadow=true;body.receiveShadow=true;model.add(body);addFace();addJomon();model.rotation.set(0,0,Math.PI);controls.target.set(0,0,S.height*.48);updateMetrics();render()}
 function render(){renderer.render(scene,camera)}function loop(){requestAnimationFrame(loop);controls.update();render()}loop();
 function resize(){var w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}new ResizeObserver(resize).observe(canvas);resize();
 function debounce(){clearTimeout(rebuildTimer);rebuildTimer=setTimeout(rebuild,45)}
 function bindRange(id,key,fmt){var el=document.getElementById(id),out=document.getElementById(id+'Val');function go(){S[key]=+el.value;if(out)out.textContent=fmt(S[key]);debounce()}el.addEventListener('input',go);go()}
 bindRange('height','height',v=>v.toFixed(0)+' mm');bindRange('radius','radius',v=>v.toFixed(0)+' mm');bindRange('belly','belly',v=>Math.round(v*100)+'%');bindRange('rough','rough',v=>Math.round(v*100)+'%');bindRange('wall','wall',v=>v.toFixed(1)+' mm');bindRange('floor','floor',v=>v.toFixed(1)+' mm');bindRange('faceSize','faceSize',v=>v.toFixed(1)+' mm');bindRange('faceHeight','faceHeight',v=>Math.round(v*100)+'%');bindRange('jomonSpace','jomonSpace',v=>v.toFixed(0)+' mm');bindRange('jomonSize','jomonSize',v=>v.toFixed(1)+' mm');
 document.querySelectorAll('#shapeSeg button').forEach(b=>b.onclick=function(){S.shape=b.dataset.value;document.querySelectorAll('#shapeSeg button').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('.vesselOnly').forEach(x=>x.hidden=S.shape!=='vessel');document.querySelectorAll('.lumpOnly').forEach(x=>x.hidden=S.shape!=='lump');S.seed=Math.floor(Math.random()*1e9);rebuild()});
 document.getElementById('randomBtn').onclick=function(){S.seed=Math.floor(Math.random()*1e9);rebuild()};
 [['eyesOn','eyes'],['mouthOn','mouth'],['earsOn','ears'],['noseOn','nose'],['jomonOn','jomon']].forEach(x=>document.getElementById(x[0]).onchange=function(){S[x[1]]=this.checked;rebuild()});
 [['eyeStyle','eyeStyle'],['mouthStyle','mouthStyle'],['earStyle','earStyle'],['jomonStyle','jomonStyle']].forEach(x=>document.getElementById(x[0]).onchange=function(){S[x[1]]=this.value;rebuild()});
 var sw=document.getElementById('swatches');colors.forEach(function(c,i){var b=document.createElement('button');b.className='swatch'+(i===0?' active':'');b.style.background=c[0];b.title=c[1];b.onclick=function(){S.color=c[0];sw.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');rebuild()};sw.appendChild(b)});
 function estimate(){var outer=Math.PI*S.radius*S.radius*S.height*(S.shape==='lump'?.72:.92),inner=S.shape==='vessel'?Math.PI*Math.max(1,S.radius-S.wall)**2*Math.max(0,S.height-S.floor)*.88:0,mm3=Math.max(1000,outer-inner);var grams=mm3/1000*1.24*1.12,price=Math.ceil(Math.max(1800,1100+grams*55)/100)*100;return{grams:grams,price:price}}
 function updateMetrics(){var e=estimate(),w=Math.round(S.radius*2.35),h=Math.round(S.height);document.getElementById('dims').textContent=w+'×'+h;document.getElementById('weight').textContent=e.grams.toFixed(0)+'g';document.getElementById('price').textContent='¥'+e.price.toLocaleString();document.getElementById('stageSize').textContent='約 '+w+' × '+h+' mm'}
 function meshTriangles(mesh){mesh.updateWorldMatrix(true,false);var g=mesh.geometry,pos=g.attributes.position,idx=g.index,m=mesh.matrixWorld,tris=[],a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();function v(i,o){return o.fromBufferAttribute(pos,i).applyMatrix4(m)}var count=idx?idx.count:pos.count;for(var i=0;i<count;i+=3){var i0=idx?idx.getX(i):i,i1=idx?idx.getX(i+1):i+1,i2=idx?idx.getX(i+2):i+2;tris.push([v(i0,a).clone(),v(i1,b).clone(),v(i2,c).clone()])}return tris}
 function stlBytes(){var tris=[];model.traverse(o=>{if(o.isMesh&&o!==ground)tris=tris.concat(meshTriangles(o))});var buf=new ArrayBuffer(84+tris.length*50),dv=new DataView(buf),off=84;dv.setUint32(80,tris.length,true);var ab=new THREE.Vector3(),ac=new THREE.Vector3(),nr=new THREE.Vector3();tris.forEach(function(p){nr.crossVectors(ab.subVectors(p[1],p[0]),ac.subVectors(p[2],p[0])).normalize();[nr,p[0],p[1],p[2]].forEach(function(v){dv.setFloat32(off,v.x,true);dv.setFloat32(off+4,v.y,true);dv.setFloat32(off+8,v.z,true);off+=12});off+=2});return new Uint8Array(buf)}
 function b64(u8){var s='',n=0x8000;for(var i=0;i<u8.length;i+=n)s+=String.fromCharCode.apply(null,u8.subarray(i,i+n));return btoa(s)}function download(){var u=stlBytes(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([u],{type:'model/stl'}));a.download='neqo-clay-'+Date.now()+'.stl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}document.getElementById('stlBtn').onclick=download;
 function preview(max){render();var c=document.createElement('canvas'),scale=Math.min(1,max/canvas.width);c.width=Math.round(canvas.width*scale);c.height=Math.round(canvas.height*scale);c.getContext('2d').drawImage(canvas,0,0,c.width,c.height);return c.toDataURL('image/png')}
 var dlg=document.getElementById('orderDlg');document.getElementById('orderBtn').onclick=function(){var e=estimate();document.getElementById('orderImg').src=preview(420);document.getElementById('orderSummary').textContent=(S.shape==='vessel'?'器':'土の塊')+'\n約 '+Math.round(S.radius*2.35)+' × '+Math.round(S.height)+' mm\nPLA 約'+e.grams.toFixed(0)+'g\n参考価格 ¥'+e.price.toLocaleString()+'（送料別・形状確認前）';document.getElementById('status').className='status';dlg.showModal()};document.getElementById('cancelBtn').onclick=()=>dlg.close();
 function spec(){var e=estimate();return{v:1,shape:S.shape,height:S.height,radius:S.radius,belly:S.belly,rough:S.rough,seed:S.seed,wall:S.wall,floor:S.floor,face:{eyes:S.eyes,mouth:S.mouth,ears:S.ears,nose:S.nose,eyeStyle:S.eyeStyle,mouthStyle:S.mouthStyle,earStyle:S.earStyle,size:S.faceSize,height:S.faceHeight},jomon:{on:S.jomon,style:S.jomonStyle,space:S.jomonSpace,size:S.jomonSize},color:S.color,grams:+e.grams.toFixed(1),priceYen:e.price}}
 function say(kind,msg){var x=document.getElementById('status');x.className='status show '+kind;x.innerHTML=msg}
 document.getElementById('orderForm').onsubmit=function(ev){ev.preventDefault();var name=document.getElementById('oName').value.trim(),mail=document.getElementById('oMail').value.trim();if(!name||!/^\S+@\S+\.\S+$/.test(mail)){say('err','お名前と正しいメールアドレスを入力してください。');return}var btn=document.getElementById('sendBtn');btn.disabled=true;btn.textContent='3Dデータを準備中…';rebuild();var data=b64(stlBytes()),png=preview(420),sp=spec(),qty=document.getElementById('oQty').value,ship=document.getElementById('oShipping').value,note=document.getElementById('oNote').value.trim();var msg=['■ ねんどのかたち 3Dプリント発注','形: '+(S.shape==='vessel'?'器':'土の塊'),'概寸: 約 '+Math.round(S.radius*2.35)+' × '+S.height+' mm','個数: '+qty,'受け取り: '+(ship==='pickup'?'直接受け取り':'配送'),'参考価格（形状確認前）: ¥'+spec().priceYen.toLocaleString()+'／個',note?'ご要望: '+note:'','SPEC='+JSON.stringify(sp)].filter(Boolean).join('\n');var payload=new URLSearchParams({hp:document.getElementById('oHidden').value,type:'ろくろ立体注文',name:name,mail:mail,message:msg,slug:'clay-'+S.shape,qty:qty,shippingMethod:ship,checkout:'0',borderStl:data,potteryStl:data,preview:png});btn.textContent='送信中…';fetch(ENDPOINT,{method:'POST',body:payload}).then(r=>r.json()).then(function(res){if(!res||!res.ok)throw Error(res&&res.reason||'rejected');say('ok','<b>発注データを受け付けました。</b><br>形状を確認し、製作可否・確定金額・お支払い方法をメールでご連絡します。');btn.textContent='受付完了'}).catch(function(e){console.error(e);say('err','送信できませんでした。時間をおいて再度お試しいただくか、NEQO FABへお問い合わせください。');btn.disabled=false;btn.textContent='見積もりを依頼する'})};
 rebuild();
})();
