(function(){'use strict';
var ENDPOINT='https://script.google.com/macros/s/AKfycbyHicngCVMmfbtBU1VuuL-Ma7-UckHde8SKVsIocotw_DMFi2eWJaM8SooKTp-mTrR1/exec';
var STRIPE_FEE_RATE=.036;
function stripeFeeIncludedYen(postageYen){return Math.ceil((postageYen/(1-STRIPE_FEE_RATE))/10)*10}
var SHIPPING={smart:{label:'スマートレター',yen:stripeFeeIncludedYen(210)},light:{label:'レターパックライト',yen:stripeFeeIncludedYen(430)},pickup:{label:'直接受け取り',yen:0}};
var AUGUST_CAMPAIGN_END_MS=Date.parse('2026-09-01T00:00:00+09:00');
function augustCampaignActive(){return Date.now()<AUGUST_CAMPAIGN_END_MS}
function yen(n){return '¥'+Math.round(n).toLocaleString()}
function orderUnitPrice(e){return augustCampaignActive()?0:e.price}
var S={shape:'lump',height:90,radius:38,belly:.08,rough:.45,seed:18273,wall:3,floor:5,outputSize:90,density:'standard',spinOn:true,spinSpeed:1.2,brush:.11,sculptOn:true,sculpt:new Array(64).fill(0),eyes:false,mouth:false,ears:false,nose:false,eyeStyle:'round',mouthStyle:'normal',earStyle:'round',faceSize:8,faceHeight:.56,faceGapX:1,faceGapY:1,faceShift:0,eyeSkew:0,mouthShift:0,earSkew:0,specialFace:'none',appendage:'none',jomon:false,jomonStyle:'diagonal',jomonSpace:9,jomonSize:2.4,keyring:false,keyringHole:5,color:'#b56f45'};
var colors=[['#b56f45','赤土'],['#d59a68','黄土'],['#d8d0ba','白土'],['#6e7469','灰土'],['#446d62','深緑'],['#76536f','葡萄']];
var densities={dense:{label:'密',infill:100,factor:1},standard:{label:'まあまあ',infill:40,factor:.57},light:{label:'軽量',infill:15,factor:.38}};
var phoneSimple=window.matchMedia('(pointer:coarse)').matches&&Math.min(window.innerWidth,window.innerHeight)<600;if(phoneSimple)document.body.classList.add('phone-simple');
var canvas=document.getElementById('view'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,1500),renderer=new THREE.WebGLRenderer({canvas:canvas,antialias:true,preserveDrawingBuffer:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputEncoding=THREE.sRGBEncoding;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
camera.up.set(0,0,1);camera.position.set(145,-190,115);var controls=new THREE.OrbitControls(camera,canvas);controls.enableDamping=true;controls.target.set(0,0,45);controls.minDistance=90;controls.maxDistance=460;controls.enabled=!phoneSimple;
scene.add(new THREE.HemisphereLight(0xfff7e8,0x33443b,1.35));var key=new THREE.DirectionalLight(0xffffff,1.5);key.position.set(-100,-130,190);key.castShadow=true;scene.add(key);var fill=new THREE.DirectionalLight(0xd9c1ff,.45);fill.position.set(120,80,80);scene.add(fill);
var ground=new THREE.Mesh(new THREE.CylinderGeometry(82,86,4,64),new THREE.MeshStandardMaterial({color:0x777b6e,roughness:.92}));ground.rotation.x=Math.PI/2;ground.position.z=-3;ground.receiveShadow=true;scene.add(ground);
var grid=new THREE.GridHelper(100,10,0x9aa08f,0x858b7d);grid.rotation.x=Math.PI/2;grid.position.z=-.8;grid.material.transparent=true;grid.material.opacity=.42;scene.add(grid);
function rulerLabel(textValue,x,z){var c=document.createElement('canvas');c.width=256;c.height=96;var ctx=c.getContext('2d');ctx.fillStyle='rgba(243,242,234,.82)';ctx.fillRect(4,12,248,72);ctx.font='700 42px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#3f493d';ctx.fillText(textValue,128,48);var tex=new THREE.CanvasTexture(c),mat=new THREE.SpriteMaterial({map:tex,transparent:true,depthTest:false}),s=new THREE.Sprite(mat);s.position.set(x,0,z);s.scale.set(24,9,1);s.renderOrder=20;return s}
var ruler=new THREE.Group(),rulerPoints=[];rulerPoints.push(-60,0,0,-60,0,100);for(var rz=0;rz<=100;rz+=10){var tick=rz%50===0?9:rz%20===0?6:4;rulerPoints.push(-60,0,rz,-60+tick,0,rz)}var rulerLine=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(rulerPoints,3)),new THREE.LineBasicMaterial({color:0x4f584b,transparent:true,opacity:.78,depthTest:false}));rulerLine.renderOrder=19;ruler.add(rulerLine);ruler.add(rulerLabel('0',-70,0),rulerLabel('50',-70,50),rulerLabel('100 mm',-70,100));scene.add(ruler);
if(phoneSimple){ruler.visible=false;grid.material.opacity=.3;document.querySelector('.badge').textContent='TOUCH CLAY';document.getElementById('stageHint').textContent='土を指で左右にひっぱって変形'}
var model=new THREE.Group();scene.add(model);var rebuildTimer=0,roughCoeffs=[];
function rng(seed){return function(){seed|=0;seed=seed+0x6D2B79F5|0;var t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function makeNoise(){var r=rng(S.seed),maxM=phoneSimple?6:7,maxMz=phoneSimple?2:3;roughCoeffs=[];for(var m=2;m<=maxM;m++)roughCoeffs.push({m:m,a:.35+r()*.65,p:r()*Math.PI*2,mz:1+Math.floor(r()*maxMz),pz:r()*Math.PI*2})}
function roughAt(a,t){if(S.shape!=='lump'||!S.rough)return 0;var n=0,w=0;roughCoeffs.forEach(function(c){n+=c.a*Math.sin(c.m*a+c.p)*Math.sin(c.mz*Math.PI*t+c.pz);w+=c.a});var fade=Math.pow(Math.max(0,Math.sin(Math.PI*t)),.38)*Math.min(1,t/.16);return S.radius*.22*S.rough*fade*n/Math.max(.001,w)}
function sculptAt(t){var x=Math.max(0,Math.min(1,t))*(S.sculpt.length-1),i=Math.floor(x),f=x-i;return S.sculpt[i]*(1-f)+S.sculpt[Math.min(S.sculpt.length-1,i+1)]*f}
function profile(t,a){var edit=sculptAt(t);if(S.shape==='vessel')return Math.max(S.wall+3,S.radius*(1+S.belly*Math.sin(Math.PI*t)-.08*Math.cos(Math.PI*t))+edit);var shoulder=Math.pow(Math.max(0,Math.sin(Math.PI*t)),.4),belly=Math.exp(-.5*Math.pow((t-.48)/.36,2));var r=S.radius*(.035+.25*Math.pow(1-t,2)+.78*shoulder+.14*belly*Math.pow(Math.max(.001,1-t),.32));return Math.max(1.2+(S.wall+4-1.2)*Math.pow(1-t,2),r+roughAt(a,t)+edit)}
function vtx(r,a,z){return new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),z)}
function clayGeometry(){var seg=72,lv=52,pos=[],outer=[];function tri(a,b,c){pos.push(a.x,a.y,a.z,b.x,b.y,b.z,c.x,c.y,c.z)}
 for(var i=0;i<lv;i++){var t=i/(lv-1),ring=[];for(var j=0;j<seg;j++){var a=j/seg*Math.PI*2;ring.push(vtx(profile(t,a),a,S.height*t))}outer.push(ring)}
 for(i=0;i<lv-1;i++)for(j=0;j<seg;j++){var n=(j+1)%seg;tri(outer[i][j],outer[i][n],outer[i+1][n]);tri(outer[i][j],outer[i+1][n],outer[i+1][j])}
 var c0=new THREE.Vector3(0,0,0);for(j=0;j<seg;j++)tri(c0,outer[0][(j+1)%seg],outer[0][j]);
 if(S.shape==='vessel'){var inner=[],start=Math.max(1,Math.round((S.floor/S.height)*(lv-1)));for(i=start;i<lv;i++){var tt=i/(lv-1),ir=[];var thick=S.wall*(1-.22*tt);for(j=0;j<seg;j++){var aa=j/seg*Math.PI*2;ir.push(vtx(Math.max(2,profile(tt,aa)-thick),aa,S.height*tt))}inner.push(ir)}for(i=0;i<inner.length-1;i++)for(j=0;j<seg;j++){n=(j+1)%seg;tri(inner[i][j],inner[i+1][n],inner[i][n]);tri(inner[i][j],inner[i+1][j],inner[i+1][n])}var last=inner.length-1;for(j=0;j<seg;j++){n=(j+1)%seg;tri(outer[lv-1][j],inner[last][n],outer[lv-1][n]);tri(outer[lv-1][j],inner[last][j],inner[last][n])}var cf=new THREE.Vector3(0,0,S.height*start/(lv-1));for(j=0;j<seg;j++)tri(cf,inner[0][j],inner[0][(j+1)%seg]);}
 else{var top=new THREE.Vector3(0,0,S.height);for(j=0;j<seg;j++)tri(top,outer[lv-1][j],outer[lv-1][(j+1)%seg]);}
 var g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.computeVertexNormals();return g}
 function clayMat(){return new THREE.MeshStandardMaterial({color:S.color,roughness:.78,metalness:0,side:THREE.DoubleSide})}
 function addSphere(name,a,z,tan,vert,rad){var r=profile(Math.max(0,Math.min(1,z/S.height)),a),g=new THREE.SphereGeometry(1,22,14),m=new THREE.Mesh(g,clayMat());m.name=name;m.scale.set(rad,tan,vert);m.rotation.z=a;m.position.set((r+rad*.52)*Math.cos(a),(r+rad*.52)*Math.sin(a),z);m.castShadow=true;model.add(m)}
 function addFace(){var q=S.faceSize,center=S.faceShift||0,z=Math.max(q*1.05,Math.min(S.height-q*.7,S.height*S.faceHeight)),r0=Math.max(10,profile(z/S.height,center)),sep=Math.min(.92,q/r0*S.faceGapX),eyeZ=Math.min(S.height-q*.4,z+q*.25*S.faceGapY),eyeLZ=Math.max(q*.5,Math.min(S.height-q*.35,eyeZ+q*(S.eyeSkew||0))),eyeRZ=Math.max(q*.5,Math.min(S.height-q*.35,eyeZ-q*(S.eyeSkew||0))),mouthZ=Math.max(q*.35,z-q*.85*S.faceGapY),mouthA=center+(S.mouthShift||0),noseZ=Math.max(q*.5,z-q*.15*S.faceGapY);if(S.eyes&&S.specialFace!=='cyclops'){if(S.eyeStyle==='round'){addSphere('eyeL',center-sep,eyeLZ,q*.48,q*.6,q*.34);addSphere('eyeR',center+sep,eyeRZ,q*.48,q*.6,q*.34)}else{var eyeHalf=Math.min(.55,(S.eyeStyle==='wide'?q*.78:q*.72)/r0),eyeTube=S.eyeStyle==='wide'?q*.34:q*.22;addSurfaceStroke('eyeL',center-sep,eyeLZ,eyeHalf,eyeTube,0);addSurfaceStroke('eyeR',center+sep,eyeRZ,eyeHalf,eyeTube,0)}}if(S.mouth&&S.specialFace!=='open-mouth'&&S.specialFace!=='monster'){if(S.mouthStyle==='small'){addSphere('mouth',mouthA,mouthZ,q*.48,q*.48,q*.34)}else{var mouthHalf=Math.min(1.05,(S.mouthStyle==='wide'?q*1.75:q*1.15)/r0);addSurfaceStroke('mouth',mouthA,mouthZ,mouthHalf,q*.28,q*.16)}}if(S.nose)addSphere('nose',center+(S.mouthShift||0)*.35,noseZ,q*.38,q*.48,q*.48);if(S.ears){var ed=S.earStyle==='rabbit'?[q*.42,q*.48,q*1.65]:S.earStyle==='wide'?[q*.45,q*.85,q*.72]:[q*.42,q*.42,q*.78],side=Math.min(2.2,(S.earStyle==='rabbit'?1.05:Math.PI/2)*S.faceGapX),ez=S.earStyle==='rabbit'?Math.min(S.height-q*.2,z+q*1.15*S.faceGapY):Math.max(q*.8,Math.min(S.height-q*.8,z)),earDelta=q*(S.earSkew||0);addSphere('earL',center-side,Math.max(q*.8,Math.min(S.height-q*.2,ez+earDelta)),ed[1],ed[2],ed[0]);addSphere('earR',center+side,Math.max(q*.8,Math.min(S.height-q*.2,ez-earDelta)),ed[1],ed[2],ed[0])}}
 function addTaperedPart(name,anchor,dir,base,height){dir.normalize();var g=new THREE.CylinderGeometry(.65,base,height,18,1,false),m=new THREE.Mesh(g,clayMat());m.name=name;m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);m.position.copy(anchor).addScaledVector(dir,height*.32);m.castShadow=true;model.add(m);addSurfaceCap(name+'Tip',anchor.clone().addScaledVector(dir,height*.82),.7)}
 function addSpecialFace(){if(!S.specialFace||S.specialFace==='none')return;var q=S.faceSize,center=S.faceShift||0,z=Math.max(q*1.05,Math.min(S.height-q*.7,S.height*S.faceHeight)),eyeZ=Math.min(S.height-q*.4,z+q*.25*S.faceGapY),mouthZ=Math.max(q*.5,z-q*.85*S.faceGapY),r0=Math.max(10,profile(mouthZ/S.height,center));function horn(name,a){var hz=Math.min(S.height-q*.18,z+q*1.05),anchor=surfacePoint(a,hz,-1.2),dir=new THREE.Vector3(Math.cos(a),Math.sin(a),.72);addTaperedPart(name,anchor,dir,q*.34,q*1.05)}function fang(name,a){var anchor=surfacePoint(a,mouthZ+q*.25,-1),dir=new THREE.Vector3(Math.cos(a)*.32,Math.sin(a)*.32,-1);addTaperedPart(name,anchor,dir,q*.23,q*.7)}function openMouth(){var pts=[],half=Math.min(.85,q*1.05/r0);for(var i=0;i<32;i++){var t=i/32*Math.PI*2;pts.push(surfacePoint(center+half*Math.cos(t),mouthZ+q*.78*Math.sin(t),q*.08))}var c=new THREE.CatmullRomCurve3(pts,true,'centripetal'),m=new THREE.Mesh(new THREE.TubeGeometry(c,72,q*.27,10,true),clayMat());m.name='openMouth';m.castShadow=true;model.add(m)}function tongue(){var low=Math.max(q*.45,mouthZ-q*1.05),pts=[surfacePoint(center,mouthZ,-1),surfacePoint(center,mouthZ-q*.45,1),surfacePoint(center,low,2.4)],c=new THREE.CatmullRomCurve3(pts,false,'centripetal'),m=new THREE.Mesh(new THREE.TubeGeometry(c,32,q*.28,10,false),clayMat());m.name='tongue';m.castShadow=true;model.add(m);addSurfaceCap('tongueTip',pts[2],q*.3)}if(S.specialFace==='many-eyes'){addSphere('extraEye1',center,eyeZ+q*.95,q*.42,q*.52,q*.34);addSphere('extraEye2',center-q/r0*.7,eyeZ+q*.7,q*.36,q*.44,q*.3);addSphere('extraEye3',center+q/r0*.7,eyeZ+q*.7,q*.36,q*.44,q*.3)}else if(S.specialFace==='cyclops'){addSphere('cyclopsEye',center,eyeZ+q*.15,q*.72,q*.88,q*.56)}else if(S.specialFace==='horns'){horn('hornL',center-.38);horn('hornR',center+.38)}else if(S.specialFace==='tongue'){tongue()}else if(S.specialFace==='open-mouth'){openMouth()}else if(S.specialFace==='fangs'){fang('fangL',center-.3);fang('fangR',center+.3)}else if(S.specialFace==='horn-eyes'){horn('hornL',center-.4);horn('hornR',center+.4);addSphere('thirdEye',center,eyeZ+q*.95,q*.46,q*.55,q*.35)}else if(S.specialFace==='monster'){openMouth();fang('fangL',center-.34);fang('fangR',center+.34);horn('hornL',center-.42);horn('hornR',center+.42)}}
 function keyringTube(){return Math.max(1.7,Math.min(2.6,S.keyringHole*.32))}function overallHeight(){if(!S.keyring)return S.height;var tube=keyringTube(),major=S.keyringHole*.5+tube;return S.height+2*major+tube*.32}
 function addKeyring(){if(!S.keyring)return;var tube=keyringTube(),major=S.keyringHole*.5+tube,r=profile(.995,0),g=new THREE.TorusGeometry(major,tube,14,56),m=new THREE.Mesh(g,clayMat());m.name='keyring';m.rotation.y=Math.PI/2;m.position.set(Math.max(.5,r-tube*.3),0,S.height+major-tube*.68);m.castShadow=true;model.add(m)}
 function addAppendages(){if(S.appendage==='tail'){var z=S.height*.3,r=profile(z/S.height,Math.PI),pts=[new THREE.Vector3(-r+1,0,z),new THREE.Vector3(-r-2,0,z+3),new THREE.Vector3(-r-5,1,z+8),new THREE.Vector3(-r-6,3,z+14)],curve=new THREE.CatmullRomCurve3(pts,false,'centripetal'),tail=new THREE.Mesh(new THREE.TubeGeometry(curve,36,3.4,12,false),clayMat());tail.name='tail';tail.castShadow=true;model.add(tail);addSurfaceCap('tailBase',pts[0],3.5);addSurfaceCap('tailTip',pts[pts.length-1],3.35)}else if(S.appendage==='flippers'){[-1,1].forEach(function(side){var a=side*.58,z=S.height*.48,r=profile(z/S.height,a),g=new THREE.SphereGeometry(1,22,14),m=new THREE.Mesh(g,clayMat());m.name=side<0?'flipperL':'flipperR';m.scale.set(3.2,4.4,9.5);m.rotation.z=a;m.rotation.x=side*.28;m.position.set((r+1.1)*Math.cos(a),(r+1.1)*Math.sin(a),z-1);m.castShadow=true;model.add(m)})}}
 function surfacePoint(a,z,offset){var t=Math.max(.015,Math.min(.985,z/S.height)),r=profile(t,a)+offset;return new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),z)}
 function addSurfaceCap(name,point,radius){var cap=new THREE.Mesh(new THREE.SphereGeometry(radius,14,9),clayMat());cap.name=name;cap.position.copy(point);cap.castShadow=true;model.add(cap)}
 function addSurfaceStroke(name,centerAngle,z,halfAngle,radius,smile){var pts=[],count=18;for(var i=0;i<=count;i++){var u=-1+2*i/count,a=centerAngle+halfAngle*u,zz=z+(smile||0)*u*u;pts.push(surfacePoint(a,zz,radius*.24))}var curve=new THREE.CatmullRomCurve3(pts,false,'centripetal'),g=new THREE.TubeGeometry(curve,count*3,radius,10,false),m=new THREE.Mesh(g,clayMat());m.name=name;m.castShadow=true;model.add(m);addSurfaceCap(name+'CapL',pts[0],radius);addSurfaceCap(name+'CapR',pts[pts.length-1],radius)}
 function tube(points,r){var curve=new THREE.CatmullRomCurve3(points,false,'centripetal'),g=new THREE.TubeGeometry(curve,Math.max(24,points.length*2),r,8,false),m=new THREE.Mesh(g,clayMat());m.name='jomon';m.castShadow=true;model.add(m)}
 function addJomon(){if(!S.jomon)return;var lo=S.height*.16,hi=S.height*.78,space=S.jomonSpace,rr=S.jomonSize*.5,off=-rr*.28;if(S.jomonStyle==='horizontal'){for(var z=lo;z<=hi;z+=space){var pts=[];for(var j=0;j<=72;j++)pts.push(surfacePoint(j/72*Math.PI*2,z,off));var c=new THREE.CatmullRomCurve3(pts,true,'centripetal'),g=new THREE.TubeGeometry(c,144,rr,8,true),m=new THREE.Mesh(g,clayMat());m.name='jomon';model.add(m)}}else{var turns=(hi-lo)/space,dirs=S.jomonStyle==='cross'?[1,-1]:[1];dirs.forEach(function(dir){for(var strand=0;strand<2;strand++){var pts=[];for(var k=0;k<=Math.ceil(turns*60);k++){var t=k/Math.ceil(turns*60),a=Math.PI*strand+dir*Math.PI*2*turns*t;pts.push(surfacePoint(a,lo+(hi-lo)*t,off))}tube(pts,rr)}})}}
 function dispose(){while(model.children.length){var o=model.children.pop();if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()}}
 var sculptDrag={active:false,orbiting:false,t:.5,lastX:0},currentFit=1,currentDims={x:0,y:0,z:0},currentCenterZ=45;
 model.rotation.z=Math.PI;
 function fitToBuildLimit(){var box=new THREE.Box3(),p=new THREE.Vector3(),corners=[];model.scale.setScalar(1);model.children.forEach(function(o){if(!o.isMesh||!o.geometry)return;o.geometry.computeBoundingBox();var b=o.geometry.boundingBox;o.updateMatrix();corners.length=0;for(var xi=0;xi<2;xi++)for(var yi=0;yi<2;yi++)for(var zi=0;zi<2;zi++)corners.push(new THREE.Vector3(xi?b.max.x:b.min.x,yi?b.max.y:b.min.y,zi?b.max.z:b.min.z).applyMatrix4(o.matrix));corners.forEach(function(c){box.expandByPoint(c)})});var size=box.getSize(p),largest=Math.max(size.x,size.y,size.z,1);currentFit=Math.min(100,S.outputSize)/largest;model.scale.setScalar(currentFit);currentDims={x:size.x*currentFit,y:size.y*currentFit,z:size.z*currentFit};currentCenterZ=(box.min.z+box.max.z)*.5*currentFit}
 function rebuild(){var angle=model.rotation.z;dispose();makeNoise();var body=new THREE.Mesh(clayGeometry(),clayMat());body.name='clay';body.castShadow=true;body.receiveShadow=true;model.add(body);addAppendages();addFace();addSpecialFace();addJomon();addKeyring();model.rotation.set(0,0,angle);fitToBuildLimit();controls.target.set(0,0,currentCenterZ);updateMetrics();render()}
 var lastFrame=performance.now();function render(){renderer.render(scene,camera)}function loop(now){requestAnimationFrame(loop);var dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(S.spinOn&&S.spinSpeed>0&&!sculptDrag.orbiting)model.rotation.z+=S.spinSpeed*dt;controls.update();render()}requestAnimationFrame(loop);
 function resize(){var w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}}new ResizeObserver(resize).observe(canvas);resize();
 controls.addEventListener('start',function(){if(!sculptDrag.active)sculptDrag.orbiting=true});controls.addEventListener('end',function(){sculptDrag.orbiting=false});
 var raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
 function rayHit(ev){var rect=canvas.getBoundingClientRect();pointer.x=((ev.clientX-rect.left)/rect.width)*2-1;pointer.y=-((ev.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);var body=model.getObjectByName('clay');if(!body)return null;var hits=raycaster.intersectObject(body,false);return hits.length?hits[0]:null}
 canvas.addEventListener('pointerdown',function(ev){if(!S.sculptOn||ev.button!==0)return;if(phoneSimple&&!S.spinOn){setSpin(true);document.getElementById('stageHint').textContent='そのまま左右に動かして、むにっと変形'}var hit=rayHit(ev);if(!hit)return;ev.preventDefault();ev.stopImmediatePropagation();var local=model.worldToLocal(hit.point.clone());sculptDrag.active=true;sculptDrag.t=Math.max(0,Math.min(1,local.z/S.height));sculptDrag.lastX=ev.clientX;controls.enabled=false;canvas.setPointerCapture(ev.pointerId);canvas.style.cursor='ew-resize'},true);
 canvas.addEventListener('pointermove',function(ev){if(!sculptDrag.active)return;ev.preventDefault();ev.stopImmediatePropagation();var dx=ev.clientX-sculptDrag.lastX;sculptDrag.lastX=ev.clientX;if(!dx)return;var sigma=Math.max(.02,S.brush),limitOut=S.radius*.72,limitIn=-S.radius*.55;for(var i=0;i<S.sculpt.length;i++){var t=i/(S.sculpt.length-1),w=Math.exp(-.5*Math.pow((t-sculptDrag.t)/sigma,2));S.sculpt[i]=Math.max(limitIn,Math.min(limitOut,S.sculpt[i]+dx*.09*w))}debounce()},true);
 function endSculpt(ev){if(!sculptDrag.active)return;ev.preventDefault();ev.stopImmediatePropagation();sculptDrag.active=false;controls.enabled=!phoneSimple;canvas.style.cursor='grab';try{canvas.releasePointerCapture(ev.pointerId)}catch(_e){}}canvas.addEventListener('pointerup',endSculpt,true);canvas.addEventListener('pointercancel',endSculpt,true);
 function debounce(){clearTimeout(rebuildTimer);rebuildTimer=setTimeout(rebuild,45)}
 function bindRange(id,key,fmt){var el=document.getElementById(id),out=document.getElementById(id+'Val');function go(){S[key]=+el.value;if(out)out.textContent=fmt(S[key]);debounce()}el.addEventListener('input',go);go()}
 bindRange('height','height',v=>v.toFixed(0)+' mm');bindRange('radius','radius',v=>v.toFixed(0)+' mm');bindRange('belly','belly',v=>Math.round(v*100)+'%');bindRange('rough','rough',v=>Math.round(v*100)+'%');bindRange('wall','wall',v=>v.toFixed(1)+' mm');bindRange('floor','floor',v=>v.toFixed(1)+' mm');bindRange('outputSize','outputSize',v=>v.toFixed(0)+' mm');bindRange('spinSpeed','spinSpeed',v=>v.toFixed(1)+' rad/s');bindRange('brush','brush',v=>Math.round(v*100)+'%');bindRange('faceSize','faceSize',v=>v.toFixed(1)+' mm');bindRange('faceGapX','faceGapX',v=>Math.round(v*100)+'%');bindRange('faceGapY','faceGapY',v=>Math.round(v*100)+'%');bindRange('faceHeight','faceHeight',v=>Math.round(v*100)+'%');bindRange('jomonSpace','jomonSpace',v=>v.toFixed(0)+' mm');bindRange('jomonSize','jomonSize',v=>v.toFixed(1)+' mm');bindRange('keyringHole','keyringHole',v=>v.toFixed(1)+' mm');
 document.querySelectorAll('#shapeSeg button').forEach(b=>b.onclick=function(){S.shape=b.dataset.value;S.sculpt.fill(0);document.querySelectorAll('#shapeSeg button').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('.vesselOnly').forEach(x=>x.hidden=S.shape!=='vessel');document.querySelectorAll('.lumpOnly').forEach(x=>x.hidden=S.shape!=='lump');S.seed=Math.floor(Math.random()*1e9);rebuild()});
 document.getElementById('randomBtn').onclick=function(){S.seed=Math.floor(Math.random()*1e9);S.sculpt.fill(0);rebuild()};
 var spinCheck=document.getElementById('spinOn'),sculptCheck=document.getElementById('sculptOn'),mobileSpin=document.getElementById('mobileSpin'),mobileMode=document.getElementById('mobileMode');
 function setSpin(on){S.spinOn=!!on;spinCheck.checked=S.spinOn;document.getElementById('spinSpeed').disabled=!S.spinOn;mobileSpin.setAttribute('aria-pressed',String(S.spinOn));mobileSpin.textContent=S.spinOn?'■ 回転停止':'▶ ろくろを回す'}
 function setSculpt(on){S.sculptOn=!!on;sculptCheck.checked=S.sculptOn;mobileMode.setAttribute('aria-pressed',String(S.sculptOn));mobileMode.textContent=S.sculptOn?'✋ 成形':'↻ 見る';document.getElementById('stageHint').textContent=S.sculptOn?'作品を左右ドラッグ：成形 ／ 空白ドラッグ：回転 ／ ホイール：ズーム':'ドラッグ：回転 ／ ホイール：ズーム'}
 spinCheck.onchange=function(){setSpin(this.checked)};sculptCheck.onchange=function(){setSculpt(this.checked)};mobileSpin.onclick=function(){setSpin(!S.spinOn)};mobileMode.onclick=function(){setSculpt(!S.sculptOn)};
 document.getElementById('mobileView').onclick=function(){camera.position.set(145,-190,115);camera.up.set(0,0,1);controls.target.set(0,0,currentCenterZ);controls.update();render()};
 document.querySelectorAll('.mobile-tab').forEach(function(btn){btn.onclick=function(){var tab=btn.dataset.tab;document.querySelectorAll('.mobile-tab').forEach(function(b){b.setAttribute('aria-selected',String(b===btn))});document.querySelectorAll('.panel[data-mobile-tab]').forEach(function(panel){panel.classList.toggle('mobile-active',panel.dataset.mobileTab===tab)});window.setTimeout(resize,0)}});
 setSpin(true);setSculpt(true);
 document.getElementById('resetSculptBtn').onclick=function(){S.sculpt.fill(0);rebuild()};
 [['eyesOn','eyes'],['mouthOn','mouth'],['earsOn','ears'],['noseOn','nose'],['jomonOn','jomon'],['keyringOn','keyring']].forEach(x=>document.getElementById(x[0]).onchange=function(){S[x[1]]=this.checked;rebuild()});
 [['eyeStyle','eyeStyle'],['mouthStyle','mouthStyle'],['earStyle','earStyle'],['jomonStyle','jomonStyle']].forEach(x=>document.getElementById(x[0]).onchange=function(){S[x[1]]=this.value;rebuild()});
 var sw=document.getElementById('swatches');colors.forEach(function(c,i){var b=document.createElement('button');b.className='swatch'+(i===0?' active':'');b.style.background=c[0];b.title=c[1];b.onclick=function(){S.color=c[0];sw.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');rebuild()};sw.appendChild(b)});
 document.querySelectorAll('#densitySeg button').forEach(function(b){b.onclick=function(){S.density=b.dataset.value;document.querySelectorAll('#densitySeg button').forEach(function(x){x.setAttribute('aria-pressed',String(x===b))});updateMetrics()}});
 function appendageLabel(){return S.appendage==='tail'?'／しっぽ付き':S.appendage==='flippers'?'／ペンギンの手付き':''}
 function estimate(){var outer=Math.PI*S.radius*S.radius*S.height*(S.shape==='lump'?.72:.92),inner=S.shape==='vessel'?Math.PI*Math.max(1,S.radius-S.wall)**2*Math.max(0,S.height-S.floor)*.88:0,mm3=Math.max(1000,outer-inner);if(S.keyring){var tube=keyringTube(),major=S.keyringHole*.5+tube;mm3+=2*Math.PI*Math.PI*major*tube*tube}if(S.appendage==='tail')mm3+=700;else if(S.appendage==='flippers')mm3+=1100;mm3*=Math.pow(currentFit,3)*densities[S.density].factor;var grams=mm3/1000*1.24*1.12,price=Math.ceil(Math.max(1800,1100+grams*55)/100)*100;return{grams:grams,price:price}}
 function roundedDims(){return[currentDims.x,currentDims.y,currentDims.z].map(function(v){return Math.min(100,Math.ceil(v-1e-6))})}
 function updateMetrics(){var e=estimate(),d=roundedDims(),label=d.join('×'),campaign=augustCampaignActive();document.getElementById('dims').textContent=label;document.getElementById('weight').textContent=e.grams.toFixed(0)+'g';document.getElementById('priceLabel').textContent=campaign?'8月キャンペーン':'参考価格';document.getElementById('price').innerHTML=campaign?'<span class="campaign-old">通常 '+yen(e.price)+'</span><br>¥0':yen(e.price);document.getElementById('finishNote').textContent=campaign?'8月31日23:59まで商品代0円。お支払いは送料のみです。材料使用量は製作管理用に計算しています。':'完成形は最大100 × 100 × 100mm。PLA／積層ピッチ0.2mmの概算です。';document.getElementById('stageSize').textContent='約 '+label+' mm';updateOrderPrice()}
 function meshTriangles(mesh){mesh.updateWorldMatrix(true,false);var g=mesh.geometry,pos=g.attributes.position,idx=g.index,m=mesh.matrixWorld,tris=[],a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();function v(i,o){return o.fromBufferAttribute(pos,i).applyMatrix4(m)}var count=idx?idx.count:pos.count;for(var i=0;i<count;i+=3){var i0=idx?idx.getX(i):i,i1=idx?idx.getX(i+1):i+1,i2=idx?idx.getX(i+2):i+2;tris.push([v(i0,a).clone(),v(i1,b).clone(),v(i2,c).clone()])}return tris}
 function stlBytes(){var tris=[];model.traverse(o=>{if(o.isMesh&&o!==ground)tris=tris.concat(meshTriangles(o))});var buf=new ArrayBuffer(84+tris.length*50),dv=new DataView(buf),off=84;dv.setUint32(80,tris.length,true);var ab=new THREE.Vector3(),ac=new THREE.Vector3(),nr=new THREE.Vector3();tris.forEach(function(p){nr.crossVectors(ab.subVectors(p[1],p[0]),ac.subVectors(p[2],p[0])).normalize();[nr,p[0],p[1],p[2]].forEach(function(v){dv.setFloat32(off,v.x,true);dv.setFloat32(off+4,v.y,true);dv.setFloat32(off+8,v.z,true);off+=12});off+=2});return new Uint8Array(buf)}
 function b64(u8){var s='',n=0x8000;for(var i=0;i<u8.length;i+=n)s+=String.fromCharCode.apply(null,u8.subarray(i,i+n));return btoa(s)}function download(){var u=stlBytes(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([u],{type:'model/stl'}));a.download='neqo-clay-'+Date.now()+'.stl';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}document.getElementById('stlBtn').onclick=download;
 function preview(max){render();var c=document.createElement('canvas'),scale=Math.min(1,max/canvas.width);c.width=Math.round(canvas.width*scale);c.height=Math.round(canvas.height*scale);c.getContext('2d').drawImage(canvas,0,0,c.width,c.height);return c.toDataURL('image/png')}
 function shareViewBegin(){var state={camera:camera.position.clone(),up:camera.up.clone(),target:controls.target.clone(),rotation:model.rotation.z,spin:S.spinOn,speed:S.spinSpeed,ruler:ruler.visible,grid:grid.visible};setSpin(false);ruler.visible=false;grid.visible=false;model.rotation.z=0;camera.position.set(230,0,currentCenterZ);camera.up.set(0,0,1);controls.target.set(0,0,currentCenterZ);controls.update();render();return state}
 function shareViewEnd(state){ruler.visible=state.ruler;grid.visible=state.grid;model.rotation.z=state.rotation;camera.position.copy(state.camera);camera.up.copy(state.up);controls.target.copy(state.target);S.spinSpeed=state.speed;document.getElementById('spinSpeed').value=state.speed;document.getElementById('spinSpeedVal').textContent=state.speed.toFixed(1)+' rad/s';setSpin(state.spin);controls.update();render()}
 function downloadBlob(blob,name){var a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url)},1200)}
 function shareOrDownload(blob,name,title){var file;try{file=new File([blob],name,{type:blob.type})}catch(_e){downloadBlob(blob,name);return}if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){navigator.share({title:title,text:'NEQO FAB ねんどのかたち工房でつくりました',files:[file]}).catch(function(err){if(!err||err.name!=='AbortError')downloadBlob(blob,name)})}else downloadBlob(blob,name)}
 document.getElementById('imageBtn').onclick=function(){var state=shareViewBegin(),data=canvas.toDataURL('image/png'),raw=atob(data.split(',')[1]),u8=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)u8[i]=raw.charCodeAt(i);shareViewEnd(state);shareOrDownload(new Blob([u8],{type:'image/png'}),'neqo-clay-front.png','わたしのねんど作品')};
 document.getElementById('videoBtn').onclick=function(){var btn=this;if(btn.disabled)return;if(!canvas.captureStream||typeof MediaRecorder==='undefined'){alert('この端末では動画生成に対応していません。正面画像をご利用ください。');return}var state=shareViewBegin(),duration=6000;S.spinSpeed=Math.PI*2/(duration/1000);setSpin(true);var stream=canvas.captureStream(30),types=['video/mp4;codecs=avc1.42E01E','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'],mime='';for(var i=0;i<types.length;i++)if(MediaRecorder.isTypeSupported(types[i])){mime=types[i];break}var recorder;try{recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined)}catch(_e){shareViewEnd(state);alert('この端末では動画生成に対応していません。');return}var chunks=[],started=Date.now();btn.disabled=true;recorder.ondataavailable=function(e){if(e.data&&e.data.size)chunks.push(e.data)};var timer=setInterval(function(){btn.textContent='録画中 '+Math.max(0,Math.ceil((duration-(Date.now()-started))/1000))+'秒'},250);recorder.onstop=function(){clearInterval(timer);stream.getTracks().forEach(function(t){t.stop()});shareViewEnd(state);btn.disabled=false;btn.textContent='回転動画を共有';var type=recorder.mimeType||mime||'video/webm',ext=type.indexOf('mp4')>=0?'mp4':'webm';shareOrDownload(new Blob(chunks,{type:type}),'neqo-clay-turntable.'+ext,'わたしのねんど作品')};recorder.start(250);setTimeout(function(){if(recorder.state!=='inactive')recorder.stop()},duration)};
 function updateCampaignUI(){var active=augustCampaignActive(),banner=document.getElementById('campaignBanner');if(banner)banner.hidden=!active}
 function paymentNotice(kind,html){var el=document.getElementById('paymentNotice');if(!el)return;el.className='payment-notice show'+(kind==='err'?' err':kind==='info'?' info':'');el.innerHTML=html+'<button type="button" aria-label="お知らせを閉じる">×</button>';el.querySelector('button').onclick=function(){el.className='payment-notice';el.innerHTML=''}}
 function handlePaymentReturn(){var q=new URLSearchParams(location.search),state=q.get('payment');if(!state)return;var sessionId=q.get('session_id')||'',clean=location.pathname+location.hash;history.replaceState({},'',clean);if(state==='cancelled'){paymentNotice('info','<b>決済は完了していません。</b> 料金は発生していません。引き続き作品を編集できます。');return}if(state!=='success'||!/^cs_[A-Za-z0-9_]+$/.test(sessionId)){paymentNotice('err','決済結果を確認できませんでした。Stripeの領収メールをご確認ください。');return}paymentNotice('ok','<b>お支払いを確認しています…</b>');fetch(ENDPOINT+'?action=paymentStatus&session_id='+encodeURIComponent(sessionId)).then(function(r){return r.json()}).then(function(res){if(!res||!res.ok||!res.paid)throw Error('not_paid');paymentNotice('ok','<b>お支払いが完了しました。</b> ご注文ありがとうございます。製作開始のご連絡をお待ちください。')}).catch(function(){paymentNotice('err','<b>決済状況を自動確認できませんでした。</b> Stripeの領収メールをご確認ください。二重に決済しないでください。')})}
 function updateOrderPrice(){var el=document.getElementById('oPrice');if(!el)return;var e=estimate(),qty=parseInt(document.getElementById('oQty').value,10)||1,method=SHIPPING[document.getElementById('oShipping').value]||SHIPPING.light,goods=orderUnitPrice(e)*qty,pickup=method===SHIPPING.pickup;el.textContent=(augustCampaignActive()?'8月キャンペーン 商品代 ':'商品代 ')+yen(goods)+' ＋ '+method.label+' '+yen(method.yen)+' ＝ 合計 '+yen(goods+method.yen)+(pickup?'（オンライン決済なし）':'（手数料込み）')}
 function updateShippingUI(){var select=document.getElementById('oShipping'),qty=parseInt(document.getElementById('oQty').value,10)||1,smart=select.querySelector('option[value="smart"]');smart.disabled=qty!==1;if(smart.disabled&&select.value==='smart')select.value='light';var key=select.value,pickup=key==='pickup',sub=document.getElementById('orderDialogSub'),note=document.getElementById('oShippingNote'),btn=document.getElementById('sendBtn');sub.textContent=pickup?'直接受け取りは商品代・送料とも0円、オンライン決済なしです。受付後、日時と場所をメールで調整します。':(augustCampaignActive()?'8月限定キャンペーンのため商品代は0円です。次のStripe画面で配送先住所を入力し、送料のみをお支払いください。':'次のStripe画面で配送先住所を入力し、商品代と送料をご確認ください。決済完了まで注文は確定しません。');note.textContent=pickup?'送料・オンライン決済はありません。受付後、受け取り日時と場所をメールで調整します。':(qty===1?'全国一律・Stripe手数料込み。住所は次の決済画面で入力します。スマートレターは追跡なし、レターパックライトは追跡ありです。':'2個以上は手数料込み450円のレターパックライトで発送します。住所は次の決済画面で入力します。');if(!btn.disabled)btn.textContent=pickup?'直接受け取りで申し込む':'住所入力・Stripe決済へ進む';updateOrderPrice()}
 var dlg=document.getElementById('orderDlg');document.getElementById('orderBtn').onclick=function(){var e=estimate(),d=roundedDims(),density=densities[S.density],priceLine=augustCampaignActive()?'8月キャンペーン 商品代 ¥0（通常 '+yen(e.price)+'）':'商品代 '+yen(e.price)+'／個';document.getElementById('orderImg').src=preview(420);document.getElementById('orderSummary').textContent=(S.shape==='vessel'?'器':'土の塊')+(S.keyring?'／金具リング付き':'')+appendageLabel()+'\n約 '+d.join(' × ')+' mm\n密度 '+density.label+'（内部充填'+density.infill+'%）\nPLA 約'+e.grams.toFixed(0)+'g\n'+priceLine;document.getElementById('status').className='status';updateShippingUI();dlg.showModal()};document.getElementById('cancelBtn').onclick=()=>dlg.close();document.getElementById('oQty').onchange=updateShippingUI;document.getElementById('oShipping').onchange=updateShippingUI;
 function spec(){var e=estimate(),density=densities[S.density];return{v:12,creatorMode:phoneSimple?'phone-simple':'full',shape:S.shape,height:S.height,radius:S.radius,belly:S.belly,rough:S.rough,seed:S.seed,wall:S.wall,floor:S.floor,outputSizeMm:S.outputSize,fitScale:+currentFit.toFixed(5),dimensionsMm:roundedDims(),density:{value:S.density,label:density.label,infillPercent:density.infill,factor:density.factor},sculpt:S.sculpt.map(v=>+v.toFixed(2)),face:{eyes:S.eyes,mouth:S.mouth,ears:S.ears,nose:S.nose,eyeStyle:S.eyeStyle,mouthStyle:S.mouthStyle,earStyle:S.earStyle,size:S.faceSize,height:S.faceHeight,gapX:S.faceGapX,gapY:S.faceGapY,shift:S.faceShift,eyeSkew:S.eyeSkew,mouthShift:S.mouthShift,earSkew:S.earSkew,special:S.specialFace},appendage:S.appendage,jomon:{on:S.jomon,style:S.jomonStyle,space:S.jomonSpace,size:S.jomonSize},keyring:{on:S.keyring,hole:S.keyringHole},color:S.color,grams:+e.grams.toFixed(1),priceYen:e.price,campaignPriceYen:orderUnitPrice(e)}}
 function say(kind,msg){var x=document.getElementById('status');x.className='status show '+kind;x.innerHTML=msg}
 document.getElementById('orderForm').onsubmit=function(ev){ev.preventDefault();var name=document.getElementById('oName').value.trim(),mail=document.getElementById('oMail').value.trim();if(!name||!/^\S+@\S+\.\S+$/.test(mail)){say('err','お名前と正しいメールアドレスを入力してください。');return}var btn=document.getElementById('sendBtn'),original=btn.textContent;btn.disabled=true;btn.textContent='3Dデータを準備中…';rebuild();var data=b64(stlBytes()),png=preview(420),sp=spec(),dims=roundedDims(),density=densities[S.density],qty=document.getElementById('oQty').value,qtyNum=parseInt(qty,10),ship=document.getElementById('oShipping').value,shipping=SHIPPING[ship],pickup=ship==='pickup',note=document.getElementById('oNote').value.trim(),goods=orderUnitPrice(estimate())*qtyNum;var msg=['■ ねんどのかたち 3Dプリント発注','形: '+(S.shape==='vessel'?'器':'土の塊')+(S.keyring?'／金具リング付き':'')+appendageLabel(),'概寸 XYZ: 約 '+dims.join(' × ')+' mm（最大100mm）','密度: '+density.label+'（内部充填'+density.infill+'%）','個数: '+qty,'商品代: '+yen(goods),shipping.label+': '+yen(shipping.yen),'合計: '+yen(goods+shipping.yen),note?'ご要望: '+note:'','SPEC='+JSON.stringify(sp)].filter(Boolean).join('\n');var payload=new URLSearchParams({hp:document.getElementById('oHidden').value,type:'ろくろ立体注文',name:name,mail:mail,message:msg,slug:'clay-'+S.shape,qty:qty,shippingMethod:ship,checkout:pickup?'0':'1',densityKey:S.density,borderStl:data,potteryStl:data,preview:png,previewPng:png});btn.textContent=pickup?'申し込み中…':'決済画面を準備中…';fetch(ENDPOINT,{method:'POST',body:payload}).then(r=>r.json()).then(function(res){if(!res||!res.ok)throw Error(res&&res.reason||'rejected');if(pickup){say('ok','<b>直接受け取りのお申し込みを受け付けました。</b><br>受け取り日時と場所をメールでご連絡します。');btn.textContent='申込完了';return}if(res.checkoutUrl){say('ok','<b>Stripeの決済画面へ移動します。</b><br>金額と送料を確認してお支払いください。');window.location.assign(res.checkoutUrl);return}say('ok','<b>発注データを受け付けました。</b><br>決済のご案内をメールでご連絡します。');btn.textContent='受付完了'}).catch(function(e){console.error(e);say('err','送信できませんでした。注文記録が届いている場合があります。重ねて送信せず、NEQO FABへお問い合わせください。');btn.disabled=false;btn.textContent=original})};
 var phoneFaceKey='',phoneFaces=[['round','small','rabbit',true,.9,.95,0,0,0,0],['wide','wide','round',false,1.05,.9,0,0,0,0],['narrow','normal','wide',true,1.12,1.05,0,0,0,0],['round','wide','wide',false,1.18,.88,0,0,0,0],['wide','small','rabbit',true,.82,1.12,0,0,0,0],['narrow','small','round',false,.96,1.08,0,0,0,0]],phoneOddFaces=[['narrow','normal','wide',true,1.12,1.05,.18,.24,-.18,0],['round','wide','wide',false,1.18,.88,-.26,-.28,.3,.18],['wide','small','rabbit',true,.82,1.12,.22,.12,.26,-.22],['narrow','small','round',false,.96,1.08,-.2,.35,-.28,.3]],phoneSpecialFaces=[['round','small','round',false,1,1,0,0,0,0,'many-eyes'],['round','normal','wide',true,1,1,0,0,0,0,'cyclops'],['wide','small','round',false,1,1,0,0,0,0,'horns'],['round','wide','wide',false,1,1,0,0,0,0,'tongue'],['round','small','round',false,1,1,0,0,0,0,'open-mouth'],['narrow','wide','wide',true,1,1,0,0,0,0,'fangs'],['round','normal','round',true,1,1,0,0,0,0,'horn-eyes'],['wide','small','wide',false,1,1,0,0,0,0,'monster']];
 var phoneClayIndex=-1,phoneClays=[['ころん',.28,86,40],['ぽってり',.44,88,41],['ごつごつ',.62,92,38],['かなりごつごつ',.74,88,40]];
 function randomizePhoneFace(refresh){var roll=Math.random(),kind=roll<.12?'odd':roll<.36?'special':'normal',pool=kind==='odd'?phoneOddFaces:kind==='special'?phoneSpecialFaces:phoneFaces,next,key,tries=0;do{next=Math.floor(Math.random()*pool.length);key=kind+'-'+next;tries++}while(key===phoneFaceKey&&tries<12);phoneFaceKey=key;var p=pool[next];S.eyes=true;S.mouth=true;S.ears=true;S.eyeStyle=p[0];S.mouthStyle=p[1];S.earStyle=p[2];S.nose=p[3];S.faceGapX=p[4];S.faceGapY=p[5];S.faceShift=p[6];S.eyeSkew=p[7];S.mouthShift=p[8];S.earSkew=p[9];S.specialFace=p[10]||'none';S.faceSize=7.2+Math.random()*1.8;S.faceHeight=.5+Math.random()*.1;if(refresh)rebuild()}
 function randomizePhoneClay(refresh){var next;do{next=Math.floor(Math.random()*phoneClays.length)}while(next===phoneClayIndex);phoneClayIndex=next;var p=phoneClays[next],rare=Math.random();S.seed=Math.floor(Math.random()*1e9);S.rough=p[1];S.height=p[2];S.radius=p[3];S.appendage=rare<.11?'tail':rare<.22?'flippers':'none';S.sculpt.fill(0);var extra=S.appendage==='tail'?'＋しっぽ':S.appendage==='flippers'?'＋ペンギンの手':'';document.getElementById('phoneClayMood').textContent='土：'+p[0]+extra+'（出力しやすい丸い形）';if(refresh)rebuild()}
 function applyPhonePreset(){function pick(a){return a[Math.floor(Math.random()*a.length)]}S.shape='lump';S.outputSize=65;S.density='standard';randomizePhoneClay(false);randomizePhoneFace(false);S.keyring=true;S.keyringHole=pick([4,4.5,5,5.5]);S.jomon=false;setSpin(false);setSculpt(true)}
 function showPhoneFront(){setSpin(false);model.rotation.z=0;camera.position.set(230,0,currentCenterZ);camera.up.set(0,0,1);controls.target.set(0,0,currentCenterZ);controls.update();document.getElementById('stageHint').textContent='正面で一時停止中・土をタッチすると回転';render()}
 function changePhoneFace(){randomizePhoneFace(false);model.rotation.z=0;rebuild();showPhoneFront()}
 if(phoneSimple){applyPhonePreset();document.getElementById('quickClayBtn').onclick=function(){randomizePhoneClay(true)};document.getElementById('quickFaceBtn').onclick=changePhoneFace;document.getElementById('quickOrderBtn').onclick=function(){document.getElementById('orderBtn').click()}}
 updateCampaignUI();handlePaymentReturn();rebuild();if(phoneSimple)showPhoneFront();
})();
